### ISSUE TITLE
there are nothing happend when I input '''mona.mona(“modules”)'''

### ISSUE THREAD

**Issue by junmoxiao** [x64dbg/mona#4]
![1](https://user-images.githubusercontent.com/9711902/33761205-26d7dffa-dc43-11e7-97a8-f5d3461ab259.png)
![2](https://user-images.githubusercontent.com/9711902/33761213-2a94928c-dc43-11e7-8328-3db06c3c5916.png)
![3](https://user-images.githubusercontent.com/9711902/33761219-2cfb6b22-dc43-11e7-91cb-1281a02a843d.png)
-------------------

**Comment by mrexodia** [comment]
Try putting x64dbg in a path without unicode characters...

**Comment by hawaii67** [comment]
First issue

`import mona`
Then
`mona.mona("help")`

Then check the Log tab.

**Comment by junmoxiao** [comment]
changed the unicode path ,the problem solved.
Thank you
